const BAD_REQUEST = 400;
const CREATED = 201;
const UNAUTHORIZED = 401;
const INTERNAL_SERVER_ERROR = 500;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const BAD_GATEWAY = 502;
const SERVICE_UNAVAILABLE = 503;
const UNPROCESSABLE_ENTITY = 422;
const OK = 200;

export {
  BAD_REQUEST,
  CREATED,
  UNAUTHORIZED,
  INTERNAL_SERVER_ERROR,
  FORBIDDEN,
  NOT_FOUND,
  BAD_GATEWAY,
  SERVICE_UNAVAILABLE,
  UNPROCESSABLE_ENTITY,
  OK
};
